train_type: 'PTI'
loss: 'l2'
seed: ${seed}
save_path: ${exp_name}

ti_epochs: 1
pt_epochs: 1

resolution: ${resolution}

log_every: 10

placeholder:
  placeholder_token: "<s1>"
  init_token: null
  num_vectors: 3

optimizer_type: 'adamw'
dtype: ${dtype}

optimizer:
  lr: 0 
  weight_decay: 0.0001
  betas: [0.9, 0.999]

ti_scheduler:
  T_0: null
  T_mult: 1
  eta_max: 0.0005
  T_up_ratio: 0.2
  gamma: 1.
  last_epoch: -1

scheduler:
  T_0: null
  T_mult: 1
  eta_max_unet: 0.0005
  eta_max_text_encoder1: 0
  eta_max_text_encoder2: 0
  T_up_ratio: 0.2
  gamma: 1.
  last_epoch: -1

lora:
  lora_rank: 16
  unet_lr: 0
  text_encoder_lr: 0